apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-store
  labels:
    app: pet-store
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: pet-store
  template:
    metadata:
      labels:
        app: pet-store
    spec:
      containers:
        - image: docker.io/andriicodefresh/pet-store:3dc75d263a49f96bd4a0113fb3246992158fc60d
          name: pet-store
          ports:
            - containerPort: 3001
