apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-store
  labels:
    app: pet-store
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: pet-store
  template:
    metadata:
      labels:
        app: pet-store
    spec:
      containers:
        - image: docker.io/andriicodefresh/pet-store:store:ddf98c7337abd06b03685b0a830ec995896169fa
          name: pet-store
          ports:
            - containerPort: 3001
