apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api2
spec:
  replicas: 2
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
        - image: nginx
          name: test-api2
          ports:
            - containerPort: 1701
