apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-store
  labels:
    app: pet-store
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: pet-store
  template:
    metadata:
      labels:
        app: pet-store
    spec:
      containers:
        - image: docker.io/andriicodefresh/pet-store:a9d86d31fc1a7a253e3bd0baa9d7d1c96c3e14b3
          name: pet-store
          ports:
            - containerPort: 3001
