apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-store
  labels:
    app: pet-store
spec:
  replicas: 1
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: pet-store
  template:
    metadata:
      labels:
        app: pet-store
        lbl: l1
    spec:
      containers:
        - image: docker.io/andriicodefresh/pet-store:1e564518b1253fd741cdcf1abc6ad7cf58937f89
          name: pet-store
          ports:
            - containerPort: 3001
